/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_xfactoryLibrarians_CoreMidiDeviceProvider */

#ifndef _Included_com_xfactoryLibrarians_CoreMidiDeviceProvider
#define _Included_com_xfactoryLibrarians_CoreMidiDeviceProvider
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: filterOfflineDevices */
#undef com_xfactoryLibrarians_CoreMidiDeviceProvider_BUFFER_SIZE
#define com_xfactoryLibrarians_CoreMidiDeviceProvider_BUFFER_SIZE 2048L
#undef com_xfactoryLibrarians_CoreMidiDeviceProvider_DEVICE_MAP_SIZE
#define com_xfactoryLibrarians_CoreMidiDeviceProvider_DEVICE_MAP_SIZE 20L
/* Inaccessible static: midiProperties */
/*
 * Class:     com_xfactoryLibrarians_CoreMidiDeviceProvider
 * Method:    getNumberOfSources
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xfactoryLibrarians_CoreMidiDeviceProvider_getNumberOfSources
  (JNIEnv *, jobject);

/*
 * Class:     com_xfactoryLibrarians_CoreMidiDeviceProvider
 * Method:    getNumberOfDestinations
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xfactoryLibrarians_CoreMidiDeviceProvider_getNumberOfDestinations
  (JNIEnv *, jobject);

/*
 * Class:     com_xfactoryLibrarians_CoreMidiDeviceProvider
 * Method:    getSource
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_xfactoryLibrarians_CoreMidiDeviceProvider_getSource
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_xfactoryLibrarians_CoreMidiDeviceProvider
 * Method:    getDestination
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_xfactoryLibrarians_CoreMidiDeviceProvider_getDestination
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_xfactoryLibrarians_CoreMidiDeviceProvider
 * Method:    getUniqueID
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_xfactoryLibrarians_CoreMidiDeviceProvider_getUniqueID
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_xfactoryLibrarians_CoreMidiDeviceProvider
 * Method:    getMidiDeviceInfo
 * Signature: (I)Lcom/xfactoryLibrarians/CoreMidiDeviceInfo;
 */
JNIEXPORT jobject JNICALL Java_com_xfactoryLibrarians_CoreMidiDeviceProvider_getMidiDeviceInfo
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_xfactoryLibrarians_CoreMidiClient */

#ifndef _Included_com_xfactoryLibrarians_CoreMidiClient
#define _Included_com_xfactoryLibrarians_CoreMidiClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xfactoryLibrarians_CoreMidiClient
 * Method:    createClient
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_xfactoryLibrarians_CoreMidiClient_createClient
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_xfactoryLibrarians_CoreMidiClient
 * Method:    disposeClient
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_xfactoryLibrarians_CoreMidiClient_disposeClient
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_xfactoryLibrarians_CoreMidiOutputPort */

#ifndef _Included_com_xfactoryLibrarians_CoreMidiOutputPort
#define _Included_com_xfactoryLibrarians_CoreMidiOutputPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xfactoryLibrarians_CoreMidiOutputPort
 * Method:    createOutputPort
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_xfactoryLibrarians_CoreMidiOutputPort_createOutputPort
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_xfactoryLibrarians_CoreMidiOutputPort
 * Method:    sendMidiMessage
 * Signature: (IILjavax/sound/midi/MidiMessage;)V
 */
JNIEXPORT void JNICALL Java_com_xfactoryLibrarians_CoreMidiOutputPort_sendMidiMessage
  (JNIEnv *, jobject, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_xfactoryLibrarians_CoreMidiInputPort */

#ifndef _Included_com_xfactoryLibrarians_CoreMidiInputPort
#define _Included_com_xfactoryLibrarians_CoreMidiInputPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xfactoryLibrarians_CoreMidiInputPort
 * Method:    createInputPort
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_xfactoryLibrarians_CoreMidiInputPort_createInputPort
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_xfactoryLibrarians_CoreMidiInputPort
 * Method:    midiPortConnectSource
 * Signature: (ILcom/xfactoryLibrarians/CoreMidiSource;)J
 */
JNIEXPORT jlong JNICALL Java_com_xfactoryLibrarians_CoreMidiInputPort_midiPortConnectSource
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_xfactoryLibrarians_CoreMidiInputPort
 * Method:    midiPortDisconnectSource
 * Signature: (IJLcom/xfactoryLibrarians/CoreMidiSource;)V
 */
JNIEXPORT void JNICALL Java_com_xfactoryLibrarians_CoreMidiInputPort_midiPortDisconnectSource
  (JNIEnv *, jobject, jint, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
