/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_co_xfactorylibrarians_coremidi4j_CoreMidiInputPort */

#ifndef _Included_uk_co_xfactorylibrarians_coremidi4j_CoreMidiInputPort
#define _Included_uk_co_xfactorylibrarians_coremidi4j_CoreMidiInputPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_co_xfactorylibrarians_coremidi4j_CoreMidiInputPort
 * Method:    createInputPort
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_uk_co_xfactorylibrarians_coremidi4j_CoreMidiInputPort_createInputPort
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     uk_co_xfactorylibrarians_coremidi4j_CoreMidiInputPort
 * Method:    createVirtualPort
 * Signature: (ILjava/lang/String;Luk/co/xfactorylibrarians/coremidi4j/CoreMidiSource;)I
 */
JNIEXPORT jint JNICALL Java_uk_co_xfactorylibrarians_coremidi4j_CoreMidiInputPort_createVirtualPort
  (JNIEnv *, jobject, jint, jstring, jobject);

/*
 * Class:     uk_co_xfactorylibrarians_coremidi4j_CoreMidiInputPort
 * Method:    disposeVirtualPort
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_uk_co_xfactorylibrarians_coremidi4j_CoreMidiInputPort_disposeVirtualPort
  (JNIEnv *, jobject, jint);

/*
 * Class:     uk_co_xfactorylibrarians_coremidi4j_CoreMidiInputPort
 * Method:    midiPortConnectSource
 * Signature: (ILuk/co/xfactorylibrarians/coremidi4j/CoreMidiSource;)J
 */
JNIEXPORT jlong JNICALL Java_uk_co_xfactorylibrarians_coremidi4j_CoreMidiInputPort_midiPortConnectSource
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     uk_co_xfactorylibrarians_coremidi4j_CoreMidiInputPort
 * Method:    midiPortDisconnectSource
 * Signature: (IJLuk/co/xfactorylibrarians/coremidi4j/CoreMidiSource;)V
 */
JNIEXPORT void JNICALL Java_uk_co_xfactorylibrarians_coremidi4j_CoreMidiInputPort_midiPortDisconnectSource
  (JNIEnv *, jobject, jint, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
