/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_co_xfactorylibrarians_coremidi4j_CoreMidiSource */

#ifndef _Included_uk_co_xfactorylibrarians_coremidi4j_CoreMidiSource
#define _Included_uk_co_xfactorylibrarians_coremidi4j_CoreMidiSource
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_co_xfactorylibrarians_coremidi4j_CoreMidiSource
 * Method:    getMicroSecondTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_uk_co_xfactorylibrarians_coremidi4j_CoreMidiSource_getMicroSecondTime
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
