/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_co_xfactorylibrarians_coremidi4j_CoreMidiClient */

#ifndef _Included_uk_co_xfactorylibrarians_coremidi4j_CoreMidiClient
#define _Included_uk_co_xfactorylibrarians_coremidi4j_CoreMidiClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_co_xfactorylibrarians_coremidi4j_CoreMidiClient
 * Method:    createClient
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_uk_co_xfactorylibrarians_coremidi4j_CoreMidiClient_createClient
  (JNIEnv *, jobject, jstring);

/*
 * Class:     uk_co_xfactorylibrarians_coremidi4j_CoreMidiClient
 * Method:    disposeClient
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_uk_co_xfactorylibrarians_coremidi4j_CoreMidiClient_disposeClient
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
