/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_co_xfactorylibrarians_coremidi4j_CoreMidiOutputPort */

#ifndef _Included_uk_co_xfactorylibrarians_coremidi4j_CoreMidiOutputPort
#define _Included_uk_co_xfactorylibrarians_coremidi4j_CoreMidiOutputPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_co_xfactorylibrarians_coremidi4j_CoreMidiOutputPort
 * Method:    createOutputPort
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_uk_co_xfactorylibrarians_coremidi4j_CoreMidiOutputPort_createOutputPort
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     uk_co_xfactorylibrarians_coremidi4j_CoreMidiOutputPort
 * Method:    sendMidiMessage
 * Signature: (IILjavax/sound/midi/MidiMessage;J)V
 */
JNIEXPORT void JNICALL Java_uk_co_xfactorylibrarians_coremidi4j_CoreMidiOutputPort_sendMidiMessage
  (JNIEnv *, jobject, jint, jint, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
